{
  "formatVersion": "1.1",
  "component": {
    "group": "com.sltr.gfmc",
    "module": "gfmc-sdk",
    "version": "1.2.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "gfmc-sdk-1.2.10.aar",
          "url": "gfmc-sdk-1.2.10.aar",
          "size": 131819,
          "sha512": "5106f451feea76fd76ebaea250b3b11813ada173ccc8a69854086dc32de5ac90cf3cbee674e0a60fb700501307fae2038b0c9abc57448bd6900496147b8cb5fb",
          "sha256": "119a7c2a5a97c9cc625ea602de23ce3218f194b060e0b140c3008ac5e75b35c5",
          "sha1": "d3c91b59fc7ab0f293b2def8f54172662c829685",
          "md5": "fb73d659a8d35f55c9acfc58f69ae673"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.android.billingclient",
          "module": "billing-ktx",
          "version": {
            "requires": "8.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "gfmc-sdk-1.2.10.aar",
          "url": "gfmc-sdk-1.2.10.aar",
          "size": 131819,
          "sha512": "5106f451feea76fd76ebaea250b3b11813ada173ccc8a69854086dc32de5ac90cf3cbee674e0a60fb700501307fae2038b0c9abc57448bd6900496147b8cb5fb",
          "sha256": "119a7c2a5a97c9cc625ea602de23ce3218f194b060e0b140c3008ac5e75b35c5",
          "sha1": "d3c91b59fc7ab0f293b2def8f54172662c829685",
          "md5": "fb73d659a8d35f55c9acfc58f69ae673"
        }
      ]
    }
  ]
}
