{
  "formatVersion": "1.1",
  "component": {
    "group": "com.sltr.gfmc",
    "module": "gfmc-sdk",
    "version": "1.2.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "gfmc-sdk-1.2.3.aar",
          "url": "gfmc-sdk-1.2.3.aar",
          "size": 127526,
          "sha512": "8120308484f74e7ea6da92d8c0dd44021c7e5af517a6457ffe90420f756d26abddbf60dae963ffd06154ee58bc64237fa142175d12ce0679a2c55ed3c3b00395",
          "sha256": "40cf1b2f799e873e6951bb3a3dc08c04b1dcac236683804328ea4b4afba72add",
          "sha1": "da32e19609dbe93dac4e6ca0baa20ce6e650f770",
          "md5": "a470de45f5994ead0096e40664a22ed3"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.android.billingclient",
          "module": "billing-ktx",
          "version": {
            "requires": "7.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "gfmc-sdk-1.2.3.aar",
          "url": "gfmc-sdk-1.2.3.aar",
          "size": 127526,
          "sha512": "8120308484f74e7ea6da92d8c0dd44021c7e5af517a6457ffe90420f756d26abddbf60dae963ffd06154ee58bc64237fa142175d12ce0679a2c55ed3c3b00395",
          "sha256": "40cf1b2f799e873e6951bb3a3dc08c04b1dcac236683804328ea4b4afba72add",
          "sha1": "da32e19609dbe93dac4e6ca0baa20ce6e650f770",
          "md5": "a470de45f5994ead0096e40664a22ed3"
        }
      ]
    }
  ]
}
