{
  "formatVersion": "1.1",
  "component": {
    "group": "com.sltr.gfmc",
    "module": "gfmc-sdk",
    "version": "1.2.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "gfmc-sdk-1.2.7.aar",
          "url": "gfmc-sdk-1.2.7.aar",
          "size": 130976,
          "sha512": "241911db0ca6d6e22d7a44e152886c572c443b921cf1f100551fab3fc522847141aba3cae6c7c97f6125583196b65bf7dc61bb34048fda71c1bc7bb7e83c3592",
          "sha256": "3313b08025ec636c754188820c7d3af4911d9f79f4e25976af5bf86cd0cb57e1",
          "sha1": "e97a6d878fa3f9d6fc5c5879610db0a88f3d7ea8",
          "md5": "3e28e36460a13e4cb5cf14773afbfa10"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.android.billingclient",
          "module": "billing-ktx",
          "version": {
            "requires": "7.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "gfmc-sdk-1.2.7.aar",
          "url": "gfmc-sdk-1.2.7.aar",
          "size": 130976,
          "sha512": "241911db0ca6d6e22d7a44e152886c572c443b921cf1f100551fab3fc522847141aba3cae6c7c97f6125583196b65bf7dc61bb34048fda71c1bc7bb7e83c3592",
          "sha256": "3313b08025ec636c754188820c7d3af4911d9f79f4e25976af5bf86cd0cb57e1",
          "sha1": "e97a6d878fa3f9d6fc5c5879610db0a88f3d7ea8",
          "md5": "3e28e36460a13e4cb5cf14773afbfa10"
        }
      ]
    }
  ]
}
